services:
  tr-sync:
    container_name: tr-sync
    # Replace <github-user> and <repo-name> with your GitHub details (must be all lowercase)
    image: ghcr.io/sstaffa/traderepublic_actualbudget_sync:latest
    env_file:
      - .env.example
      - .env
    ports:
      - 8033:8000
    restart: unless-stopped
    volumes:
      # Mount only the data directory for persistent files (e.g., pytr cookies or databases)
      # Do NOT mount the local source code here to avoid overriding the container's built image
      - ./data:/data
      - ./.env:/app/.env:ro
    environment:
      - TZ=Europe/Berlin
      - APP_MODE=${APP_MODE:-production}
    networks:
      - backend

  watchtower:
    image: nickfedor/watchtower:latest
    container_name: watchtower_tr
    restart: unless-stopped
    volumes:
      # Grant Watchtower access to the Docker socket to inspect and restart containers
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/Berlin
      - WATCHTOWER_POLL_INTERVAL=300 # Check for updated images every 5 minutes (300 seconds)
      - WATCHTOWER_CLEANUP=true      # Automatically remove old, unused images after updating
    # Restrict Watchtower to only monitor the 'tr-sync' container
    command: tr-sync
    networks:
      - backend

networks:
  backend:
    external: true
